name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: prettier
        run: yarn prettier
      - name: typecheck 
        run: yarn tsc
      - name: lint 
        run: yarn lint

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          # CodeMirror uses a contenteditable div to render the editor, but 
          # Cypress does not support contenteditable elements in chromium,
          # so we just run the tests in Firefox
          browser: firefox



